FROM almalinux:8
WORKDIR /tmp
ADD https://raw.githubusercontent.com/daws-76s/notes/master/session-03.txt /tmp/
CMD ["sleep","100"]
LABEL PLATFORM="Testing" \
      OWNER="Naresh" \
      org.opencontainers.image.authors="naresh1@gmail.com"
      
      